---
- name: Check is chezmoi installed
  shell: command -v chezmoi >/dev/null 2>&1
  register: is_chezmoi_exist
  ignore_errors: yes

- name: Check is op installed
  shell: command -v op >/dev/null 2>&1
  register: is_op_exist
  ignore_errors: yes

# - debug: msg="{{ is_chezmoi_exist.rc }}" # it returns rc 0
# - debug: var=is_chezmoi_exist

- name: Setup chezmoi on rhel8
  ansible.builtin.shell: sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b $HOME/.local/bin
  args:
    executable: /bin/bash
  when: is_chezmoi_exist.failed

- name: Setup 1Password-cli on rhel8
  ansible.builtin.shell: |
    curl -sSfo op.zip https://cache.agilebits.com/dist/1P/op2/pkg/v2.7.0/op_linux_amd64_v2.7.0.zip
    unzip -od /usr/local/bin/ op.zip
    rm op.zip
    op --version
  when: is_op_exist.failed
  become: true

# install 1Password-cli

# https://snapcraft.io/install/chezmoi/rhel 